// src/components/FruitList.jsx
import React, { useState } from 'react';

function FruitList() {
  const [fruits, setFruits] = useState([]);

  const addFruit = (e) => {
    e.preventDefault();
    if (!e.target[0].value) return;
    let value = e.target[0].value;

    setFruits([...fruits, value]);
    document.getElementById('react-input').value = null;
  };

  return (
    <div>
      <h2>React Fruits!</h2>
      <form onSubmit={addFruit}>
        <input type="text" id="react-input" />
        <button type="submit">Add Fruit</button>
      </form>
      <ul>
        {fruits
          .sort((a, b) => a.localeCompare(b))
          .map((fruit) => (
            <li key={fruit}>{fruit}</li>
          ))}
      </ul>
      <strong>Total Fruits:</strong> {fruits.length}
    </div>
  );
}

export default FruitList;

// src/components/FruitList.vue
<script setup>
import { ref, reactive, computed } from 'vue';

const fruitToAdd = ref();

const fruits = reactive([]);

const fruitsSorted = computed(() => {
  let array = Array.from(fruits);
  return array.sort((a, b) => a.localeCompare(b));
})

const total = computed(() => {
  let total = Array.from(fruits);
  return total.length;
});

const addFruit = (e) => {
  e.preventDefault();
  if (!fruitToAdd.value) return;
  fruits.push(fruitToAdd.value);
  fruitToAdd.value = null;
};

</script>

<template>
  <div>
    <h2>Vue Fruits!</h2>

    <form @submit="addFruit">
      <input type="text" v-model="fruitToAdd" />
      <button type="submit">Add Fruit</button>
    </form>

    <ul>
      <li v-for="(item, index) in fruitsSorted" :key="index">
        {{item}}
      </li>
    </ul>

    <strong>Total Fruits:</strong> {{ total }}
  </div>
</template>

<style scoped lang="scss">

</style>
